GET http://localhost:8888/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhaG1ldC5iZWt0YXNzODFAaG90bWFpbC5jb20iLCJqdGkiOiJkNDg5YzVhYi00ZGY1LTRmNWItYjUyMS1jNTVkOTQyNWVlMDMiLCJ1bmlxdWVfbmFtZSI6ImFobWV0LmJla3Rhc3M4MUBob3RtYWlsLmNvbSIsImV4cCI6MTcyNDQyNTA1MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4In0.H3a9ME6VDPVF-NAMPV7Nmh9m34LGT3Qo51ktJ1UkC80

###
GET http://localhost:8888/api/customers/1/timebills

###
GET http://localhost:8888/api/customers/Paintorama
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhaG1ldC5iZWt0YXNzODFAaG90bWFpbC5jb20iLCJqdGkiOiJkZTQ1ZTU0NS1mNWM5LTQ0N2EtOWQ0YS02MDVlMGY2MTYyZjIiLCJ1bmlxdWVfbmFtZSI6ImFobWV0LmJla3Rhc3M4MUBob3RtYWlsLmNvbSIsImV4cCI6MTcyNDQyMDkyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4ODg4In0.rzxBuULR7b5IhV0w6TL__K-a83jjt7jF7UiXAFC8ojg

###
GET http://localhost:8888/api/timebills/1

###
POST http://localhost:8888/api/timebills
Content-Type: application/json

{
  "hoursWorked": 2.5,
  "rate": 125.00,
  "date": "2024-08-19",
  "work": "Added work perfomed",
  "customerId": 1,
  "employeeId": 1
}
###
POST http://localhost:8888/api/auth/token
Content-Type: application/json

{
  "userName": "ahmet.bektass81@hotmail.com",
  "password": "Ahmet123."
}